"""Change subtask class attribute doneness

Revision ID: 2a7d48df4224
Revises: be948209c30e
Create Date: 2022-04-01 18:00:05.788852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7d48df4224'
down_revision = 'be948209c30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('is_done', sa.Boolean(), nullable=False))
    op.drop_column('subtask', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('done', sa.BOOLEAN(), nullable=False))
    op.drop_column('subtask', 'is_done')
    # ### end Alembic commands ###
