"""Change subtask class attribute doneness

Revision ID: be948209c30e
Revises: bee2e14c756c
Create Date: 2022-04-01 17:55:11.957832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be948209c30e'
down_revision = 'bee2e14c756c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('done', sa.Boolean(), nullable=False))
    op.drop_column('subtask', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('status', sa.VARCHAR(length=8), nullable=True))
    op.drop_column('subtask', 'done')
    # ### end Alembic commands ###
